[project]
name = "llm-custom"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Luciano Griffith", email = "luciano.griffith@lore-finance.com" }
]
requires-python = ">=3.9"
dependencies = [
    "tiktoken>=0.14.0",
]

[project.scripts]
llm-custom = "llm_custom:main"

[build-system]
requires = ["uv_build>=0.12.14,<0.13.0"]
build-backend = "uv_build"
